version: '3'

networks:
  nestjsx_crud:

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjsx_crud
    networks:
      - nestjsx_crud

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: nestjsx_crud
      MYSQL_USER: nestjsx_crud
      MYSQL_PASSWORD: nestjsx_crud
      MYSQL_ROOT_PASSWORD: nestjsx_crud
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server
    networks:
      - nestjsx_crud