name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: nestjsx_crud
        ports:
          - 5432:5432
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: nestjsx_crud
          MYSQL_USER: nestjsx_crud
          MYSQL_PASSWORD: nestjsx_crud
          MYSQL_ROOT_PASSWORD: nestjsx_crud
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - name: Build the project
        run: yarn build

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: yarn nx-cloud record -- echo Hello World
      - run: yarn nx affected -t lint test build

      - name: Test all
        run: yarn test:coverage

      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: yarn nx fix-ci
        if: always()
